version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '3308:5432'
  api:
    build: .
    container_name: api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
